# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'Epispy 2.0' do

use_frameworks!
pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
pod 'Kingfisher', '~> 2.2'
pod 'Alamofire', '~> 3.0'
pod 'BRYXBanner'
pod 'SlideMenuControllerSwift'
end

target 'Epispy 2.0Tests' do

end

